wezterm again, removed titles from scratchpad.sh

diff --git a/.local/bin/wa b/.local/bin/wa
--- a/.local/bin/wa
+++ b/.local/bin/wa
@@ -2,36 +2,36 @@
 
 WA_APPID=$(<$HOME/.wolfram_api_key)
 
-VIEWER="kitty +kitten icat --align left"
+VIEWER="wezterm imgcat --no-resample"
+# VIEWER="kitty +kitten icat --align left"
 BG="transparent"
 FG="white"
 # BG="white"
 # FG="black"
 
 [[ $WA_APPID ]] || {
-  printf 'ERROR: $WA_APPID is not set.\nGet one at https://products.wolframalpha.com/api\n'
-  exit 1
+    printf 'ERROR: $WA_APPID is not set.\nGet one at https://products.wolframalpha.com/api\n'
+    exit 1
 }
 
 if [[ $1 = "-p" ]]; then
-  shift
-  curl -s -w '\n' "https://api.wolframalpha.com/v1/simple?appid=${WA_APPID}&units=metric&foreground=${FG}&background=${BG}" \
-    --data-urlencode "i=$*" | $VIEWER
-  exit 0
+    shift
+    curl -s -w '\n' "https://api.wolframalpha.com/v1/simple?appid=${WA_APPID}&units=metric&foreground=${FG}&background=${BG}" \
+        --data-urlencode "i=$*" | $VIEWER
+    exit 0
 fi
 
 RESPONSE=$(
-  curl -s "https://api.wolframalpha.com/v1/result?appid=${WA_APPID}&units=metric&" \
-    --data-urlencode "i=$*"
+    curl -s "https://api.wolframalpha.com/v1/result?appid=${WA_APPID}&units=metric&" \
+        --data-urlencode "i=$*"
 )
 
 if [[ "No short answer available" = "$RESPONSE" ]]; then
-  printf "No short answer available, downloading full answer...\n"
-  curl -s -w '\n' "https://api.wolframalpha.com/v1/simple?appid=${WA_APPID}&units=metric&foreground=${FG}&background=${BG}" \
-    --data-urlencode "i=$*" | $VIEWER
+    printf "No short answer available, downloading full answer...\n"
+    curl -s -w '\n' "https://api.wolframalpha.com/v1/simple?appid=${WA_APPID}&units=metric&foreground=${FG}&background=${BG}" \
+        --data-urlencode "i=$*" | $VIEWER
 else
-  printf '%s\n' "$RESPONSE"
+    printf '%s\n' "$RESPONSE"
 fi
 
 exit 0
-
